---

- hosts: all
  become: true
  tasks:

  - name: update repositories
    apt:
      update_cache: yes 
    when: ansible_distribution in ['Ubuntu','Debian']


  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install httpd package for CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == 'CentOS'

  - name: add php support for httpd-CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == 'CentOS'



