---

- hosts: all
  become: true
  tasks:

  - name: update repositories for ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install apche2 and php packages for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: update repositories for CentOS
    apt:
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: install httpd and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'CentOS'
