---

- hosts: all
  become: yes
  tasks:

  - name: install apache and php for ubuntu
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install apache and php for CentOS
    dnf:
      name:
        - httpd
        - php
      update_cache: yes
    when: ansible_distribution == 'CentOS'


