---

- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates ubuntu
    tags: update
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install updates in centos
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == 'CentOS'


- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache and php for ubuntu
    tags: apache, apache2, ubuntu
    apt:
       name:
          - apache2
          - libapache2-mod-php
       state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: copy files to web servers
    tags: copy, apache, ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == 'Ubuntu'


- hosts: workstations
  become: true
  tasks:


  - name: install unzip
    tags: unzip
    package:
      name: unzip
      state: latest

  - name: install terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


#  - name: install apache and php for CentOS
#    tags: apache, centos
#    dnf:
#      name:
#        - httpd
#        - php
#      state: latest
#    when: ansible_distribution == 'CentOS'

- hosts: db_servers
  become: true
  tasks:

  - name: installing mariadb package CentOS
    tags: mariadb, centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == 'CentOS'

  - name: installing mariadb package Ubuntu
    tags: mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'
    
